### ISSUE TITLE
TODO v4

### ISSUE THREAD

**Issue by seiya-git** [seiya-dev/funimation-downloader-nx#28]
- [x] Drop m3u8-stream-list module
- [x] Reconfigurable default parameters for options
- [x] Reconfigurable default video directory and trash directory
- [ ] Skip muxing if mp4box with tsmuxer or mkvmerge not detected
- [ ] Option to do demux before mux into mkv
- [ ] Switch muxing to mkv if mp4box or tsmuxer not detected
- [x] Improve ttml (.dfxp) parsing
- [ ] Switching between available servers
- [x] Option to turn off trash folder / removing files completely
